#include "register.cpp";
#include "login.cpp";
#include "change_pass.cpp";
void execute_choice(int choice);
int getUserChoice();
void clearScreen();
void ignoreLine();
bool isValidChoice(int choice);
bool validName(string name);
bool validpassword(string password);
bool validEmail(string email);
bool validphonenumber(string phone_number);
void maskingpassword(string& password);
void passEncryption(string& password);
void passDecryption(string& password);
void compare();
void split(string str, vector<string>& splitedData);
void Registeration();
void login();
void change_password();
void save();